import type { AnswerFinderEntry } from './AnswerFinder';

export type AnswerFinderLanguage = 'en' | 'zh';

/**
 * Controlled Answer Finder index.
 *
 * Rules:
 * - Every entry must point to an existing ID Work Studio page or tool.
 * - Short answers are summaries only; the linked page remains the source of truth.
 * - projectSpecific=true means the question may require unit/scope-specific confirmation.
 * - Do not add guessed section anchors. Use verified page URLs until stable IDs are confirmed.
 * - Keep one canonical owner per question to avoid competing answers.
 */

const en: AnswerFinderEntry[] = [
  {
    id: 'renovation-cost-singapore',
    question: 'How much does renovation cost in Singapore?',
    answer:
      'Renovation cost depends on property type, condition and scope. In 2026, broad planning ranges on ID Work Studio’s guide start from about S$40,000 for some BTO projects and rise substantially for resale, condo and more complex scopes.',
    href: '/insights/renovation-cost-singapore-2026',
    linkLabel: 'Read renovation cost guide',
    keywords: [
      'renovation cost',
      'renovation price',
      'home renovation budget',
      'how much renovation',
      'Singapore renovation cost',
      'BTO renovation cost',
      'resale renovation cost',
      'condo renovation cost',
    ],
    category: 'Residential Cost',
    relatedIds: ['kitchen-renovation-cost', 'quotation-differences', 'total-home-budget'],
  },
  {
    id: 'hdb-renovation-timeline',
    question: 'How long does an HDB renovation usually take?',
    answer:
      'HDB renovation timing depends on scope, approvals, hacking, carpentry, materials and coordination. Use the HDB timeline guide to plan the sequence rather than relying on one fixed completion date.',
    href: '/insights/hdb-renovation-timeline-singapore',
    linkLabel: 'Read HDB timeline guide',
    keywords: [
      'HDB renovation timeline',
      'how long HDB renovation',
      'HDB renovation duration',
      'when can I move in',
      'renovation weeks',
      'BTO renovation timeline',
      'resale renovation timeline',
    ],
    category: 'Residential Timeline',
    relatedIds: ['renovation-cost-singapore', 'hdb-defects-before-renovation'],
  },
  {
    id: 'quotation-differences',
    question: 'Why are my renovation quotations so different?',
    answer:
      'Two quotations can differ because they are not pricing the same scope, materials, quantities, risk or exclusions. Compare them line by line rather than comparing only the final total.',
    href: '/insights/renovation-quotation-singapore',
    linkLabel: 'Read quotation comparison guide',
    keywords: [
      'quotation difference',
      'quotes different',
      'renovation quotes',
      'compare contractor quotes',
      'why one quote cheaper',
      'cheap renovation quote',
      'quotation too expensive',
    ],
    category: 'Quotation',
    relatedIds: ['variation-orders', 'renovation-cost-singapore'],
  },
  {
    id: 'variation-orders',
    question: 'Are renovation variation orders normal?',
    answer:
      'Some variation orders are reasonable when hidden site conditions appear or when the homeowner changes the scope. The risk is when essential work was omitted from the original quotation just to make the starting price look lower.',
    href: '/insights/renovation-quotation-singapore',
    linkLabel: 'Read about variation orders',
    keywords: [
      'variation order',
      'VO',
      'extra charges renovation',
      'renovation add on cost',
      'contractor asking more money',
      'unexpected renovation charges',
    ],
    category: 'Quotation',
    relatedIds: ['quotation-differences'],
  },
  {
    id: 'hdb-defects-before-renovation',
    question: 'What should I check before HDB renovation starts?',
    answer:
      'Inspect and document defects before major renovation begins. Check water flow, hollow tiles, windows, doors, meters, dampness, floor gradients and other conditions that could later affect renovation scope or responsibility.',
    href: '/insights/hdb-defect-checklist-before-renovation-singapore',
    linkLabel: 'Open HDB defect guide',
    keywords: [
      'HDB defects',
      'BTO defects',
      'defect inspection',
      'before renovation check',
      'hollow tiles',
      'water leak before renovation',
      'defect checklist',
    ],
    category: 'Residential Planning',
    relatedIds: ['hdb-renovation-timeline'],
  },
  {
    id: 'overseas-renovation-items',
    question: 'Can I buy renovation items from Taobao or overseas?',
    answer:
      'Yes, but check exact dimensions, lift access, Singapore voltage, SAFETY Mark or WELS requirements where relevant, warranty, spare parts, shipping damage risk and delivery timing before ordering.',
    href: '/insights/overseas-renovation-shopping-singapore',
    linkLabel: 'Read overseas shopping guide',
    keywords: [
      'Taobao renovation',
      'buy from China',
      'overseas furniture',
      'import renovation items',
      'overseas taps',
      'overseas appliance',
      'China tiles',
      'Amazon renovation',
    ],
    category: 'Residential Planning',
    relatedIds: ['hdb-renovation-timeline'],
  },
  {
    id: 'feng-shui-before-renovation',
    question: 'Should I consider feng shui before renovation starts?',
    answer:
      'If feng shui affects layout, lighting, storage or circulation, it is better to discuss it before carpentry and electrical plans are finalised. Practical function should still come before decorative symbolism.',
    href: '/insights/feng-shui-renovation-singapore',
    linkLabel: 'Read feng shui renovation guide',
    keywords: [
      'feng shui renovation',
      'fengshui renovation',
      'feng shui before renovation',
      'feng shui layout',
      'feng shui HDB',
    ],
    category: 'Residential Planning',
  },
  {
    id: 'kitchen-renovation-cost',
    question: 'How much does a kitchen renovation cost?',
    answer:
      'Kitchen renovation cost depends heavily on hacking, tiling, carpentry length, worktop material, plumbing, electrical works and the existing site condition. Use the kitchen cost guide for a proper breakdown.',
    href: '/insights/kitchen-renovation-cost-singapore-2026',
    linkLabel: 'Read kitchen cost guide',
    keywords: [
      'kitchen renovation cost',
      'kitchen price',
      'HDB kitchen renovation',
      'kitchen cabinet cost',
      'kitchen hacking cost',
      'kitchen budget',
    ],
    category: 'Residential Cost',
    relatedIds: ['renovation-cost-singapore'],
  },
  {
    id: 'total-home-budget',
    question: 'How much cash should I prepare beyond the renovation contract?',
    answer:
      'Renovation is only part of the move-in budget. Furniture, appliances, fees, replacements and a safety buffer can materially change the amount of cash you need before moving in.',
    href: '/insights/real-cost-moving-home-singapore',
    linkLabel: 'Read full move-in budget guide',
    keywords: [
      'move in budget',
      'cash needed renovation',
      'furniture appliance budget',
      'renovation plus furniture',
      'total home cost',
      'how much cash to prepare',
    ],
    category: 'Residential Cost',
    relatedIds: ['renovation-cost-singapore'],
  },
  {
    id: 'hdb-wall-hacking',
    question: 'Can I hack this wall in my HDB flat?',
    answer:
      'This cannot be confirmed safely from a generic website answer. Whether a wall can be removed depends on the specific flat, approved plans, structural status and the proposed works.',
    href: '/residential',
    linkLabel: 'View residential renovation',
    keywords: [
      'hack HDB wall',
      'remove HDB wall',
      'can this wall be hacked',
      'demolish wall',
      'structural wall HDB',
      'wall hacking approval',
    ],
    category: 'Project Specific',
    projectSpecific: true,
  },

  {
    id: 'commercial-renovation-cost',
    question: 'How much does commercial renovation cost in Singapore?',
    answer:
      'Commercial renovation cost depends on business type, building rules, M&E requirements and approvals. Offices, retail, clinics and F&B units can have very different cost structures even at similar floor areas.',
    href: '/insights/commercial-renovation-cost-singapore',
    linkLabel: 'Read commercial cost guide',
    keywords: [
      'commercial renovation cost',
      'shop renovation cost',
      'retail renovation cost',
      'commercial fit out cost',
      'commercial renovation price',
      'cost per sqft commercial',
    ],
    category: 'Commercial Cost',
    relatedIds: ['office-renovation-cost', 'fnb-renovation-cost'],
  },
  {
    id: 'office-renovation-cost',
    question: 'How much does office renovation cost in Singapore?',
    answer:
      'Office renovation cost depends on fit-out level, partitions, electrical and data works, air-conditioning, fire-safety coordination, finishes and building requirements. Use the office cost guide for current ranges by size and scope.',
    href: '/insights/office-renovation-cost-singapore',
    linkLabel: 'Read office cost guide',
    keywords: [
      'office renovation cost',
      'office fit out cost',
      'office renovation price',
      'office cost per sqft',
      '1000 sqft office cost',
      'office renovation budget',
      'normal office renovation cost',
    ],
    category: 'Office Cost',
    relatedIds: ['office-renovation-timeline', 'office-space-needed'],
  },
  {
    id: 'fnb-renovation-cost',
    question: 'Why is F&B renovation usually more expensive than office renovation?',
    answer:
      'F&B projects usually require heavier M&E coordination such as exhaust, grease control, plumbing, waterproofing, kitchen equipment and fire-safety work. These technical systems can cost more than the visible interior finishes.',
    href: '/insights/commercial-renovation-cost-singapore',
    linkLabel: 'Read commercial and F&B cost guide',
    keywords: [
      'F&B renovation cost',
      'restaurant renovation cost',
      'cafe renovation cost',
      'why F&B expensive',
      'food shop renovation price',
      'restaurant fit out cost',
    ],
    category: 'F&B Cost',
    relatedIds: ['fnb-before-signing-lease', 'fnb-exhaust-feasibility'],
  },
  {
    id: 'office-renovation-timeline',
    question: 'How long does office renovation take in Singapore?',
    answer:
      'As a working guide, a small office usually takes about 3–6 weeks, a medium office 6–10 weeks, and a large or corporate office 10–16 weeks when planning, approvals, site works and handover are included.',
    href: '/insights/office-renovation-timeline-singapore',
    linkLabel: 'Read office timeline guide',
    keywords: [
      'office renovation timeline',
      'how long office renovation',
      'office fit out duration',
      'office renovation weeks',
      'office move in date',
      'office completion time',
    ],
    category: 'Office Timeline',
    relatedIds: ['office-two-week-renovation', 'office-renovation-cost'],
  },
  {
    id: 'office-two-week-renovation',
    question: 'Can an office renovation be completed in 2 weeks?',
    answer:
      'Only very small cosmetic refresh works may fit into about two weeks. A proper office fit-out with partitions, electrical, data, air-conditioning and landlord approval normally needs more time.',
    href: '/insights/office-renovation-timeline-singapore',
    linkLabel: 'See realistic office timelines',
    keywords: [
      'office renovation 2 weeks',
      'fast office renovation',
      'rush office renovation',
      'two week office fit out',
      'office renovation urgently',
      'can finish office fast',
    ],
    category: 'Office Timeline',
    relatedIds: ['office-renovation-timeline'],
  },
  {
    id: 'office-operate-during-renovation',
    question: 'Can my business continue operating during office renovation?',
    answer:
      'Sometimes, but occupied-office renovation usually needs phasing, dust and noise control, safety separation, access planning and careful power or data cutover. It normally takes longer than renovating a vacant office.',
    href: '/insights/office-renovation-timeline-singapore',
    linkLabel: 'Read business continuity guidance',
    keywords: [
      'operate during renovation',
      'work during office renovation',
      'staff stay during renovation',
      'occupied office renovation',
      'renovate office while working',
      'phased office renovation',
    ],
    category: 'Office Timeline',
    relatedIds: ['office-after-hours-renovation'],
  },
  {
    id: 'office-after-hours-renovation',
    question: 'Can office renovation be done at night or on weekends?',
    answer:
      'Yes, if the building allows it. Night, weekend and noisy works may require separate approval and can increase labour cost or extend the schedule.',
    href: '/insights/office-renovation-timeline-singapore',
    linkLabel: 'Read office timeline guide',
    keywords: [
      'night renovation',
      'weekend renovation',
      'after hours renovation',
      'office renovation at night',
      'noisy works timing',
      'commercial renovation working hours',
    ],
    category: 'Office Timeline',
    relatedIds: ['office-renovation-timeline'],
  },
  {
    id: 'office-landlord-approval',
    question: 'Do I need landlord or building management approval for office renovation?',
    answer:
      'Yes. Most Singapore office renovations require landlord or building-management approval before work can start, with documents such as drawings, work schedules, method statements, contractor details and insurance commonly requested.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read commercial approvals guide',
    keywords: [
      'landlord approval office',
      'building management approval',
      'office renovation permit',
      'permit to work office',
      'management approval renovation',
      'office fit out approval',
    ],
    category: 'Commercial Approval',
    relatedIds: ['office-mcst-approval', 'office-scdf-approval'],
  },
  {
    id: 'office-mcst-approval',
    question: 'Do I need MCST approval for office renovation?',
    answer:
      'If the office is in a strata-titled property, MCST or managing-agent approval is commonly required before renovation works can start. The actual document list depends on the building.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read commercial approvals guide',
    keywords: [
      'MCST approval',
      'MCST office renovation',
      'strata office renovation',
      'managing agent approval',
      'MCST permit',
    ],
    category: 'Commercial Approval',
    relatedIds: ['office-landlord-approval', 'office-scdf-approval'],
  },
  {
    id: 'office-scdf-approval',
    question: 'Do I need fire or SCDF approval for office renovation?',
    answer:
      'SCDF-related review may be required when the renovation affects fire-safety provisions such as partitions, escape routes, fire-rated construction, sprinklers, alarms, smoke detectors or occupant load. A Qualified Person should assess the actual scope where applicable.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read SCDF and approval guide',
    keywords: [
      'fire approval office',
      'SCDF office renovation',
      'fire safety approval',
      'office fire permit',
      'SCDF submission',
      'sprinkler approval',
      'fire alarm office renovation',
    ],
    category: 'Commercial Approval',
    relatedIds: ['office-landlord-approval', 'commercial-skip-scdf'],
    projectSpecific: true,
  },
  {
    id: 'commercial-skip-scdf',
    question: 'Can I skip SCDF submission for a simple commercial renovation?',
    answer:
      'Possibly only when the works are genuinely cosmetic and do not affect fire-safety provisions. If partitions, ceilings, sprinklers, alarms, escape routes or fire-rated elements are affected, SCDF-related submission may be required.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read SCDF approval guide',
    keywords: [
      'skip SCDF',
      'no SCDF needed',
      'simple renovation SCDF',
      'cosmetic renovation SCDF',
      'do I need SCDF',
      'SCDF exempt',
    ],
    category: 'Commercial Approval',
    projectSpecific: true,
  },
  {
    id: 'commercial-permit-rejected',
    question: 'What happens if MCST or building management rejects my renovation permit?',
    answer:
      'Work cannot start until the submission is accepted. Rejections commonly involve incomplete drawings, missing documents or insurance, contractor requirements, or proposed works that do not follow building rules.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read approval troubleshooting guide',
    keywords: [
      'permit rejected',
      'MCST reject renovation',
      'management reject permit',
      'renovation application rejected',
      'permit to work rejected',
    ],
    category: 'Commercial Approval',
    relatedIds: ['office-landlord-approval'],
  },
  {
    id: 'commercial-rent-free-period',
    question: 'Is one month of rent-free renovation period enough?',
    answer:
      'Not always. Design, measurements, management review, insurance, deposits and work-permit clearance can consume part of the rent-free period before physical construction starts.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read lease-to-opening planning guide',
    keywords: [
      'rent free period enough',
      'renovation free period',
      'one month rent free',
      'fit out period',
      'lease renovation period',
      'free rental renovation',
    ],
    category: 'Commercial Planning',
    relatedIds: ['commercial-before-lease', 'office-renovation-timeline'],
  },
  {
    id: 'commercial-before-lease',
    question: 'What should I check before signing a commercial lease for renovation?',
    answer:
      'Check whether the intended business use is suitable for the unit, obtain the latest fit-out guide, review electrical, air-conditioning, drainage, exhaust and structural constraints, and identify the likely approval pathway before fixing the opening date.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read commercial approval planning guide',
    keywords: [
      'before signing commercial lease',
      'check commercial unit',
      'before renting shop',
      'commercial lease renovation',
      'unit feasibility',
      'before taking over unit',
    ],
    category: 'Commercial Planning',
    relatedIds: ['fnb-before-signing-lease', 'commercial-rent-free-period'],
  },
  {
    id: 'office-space-needed',
    question: 'How much office space do I need?',
    answer:
      'Office size should be planned around headcount, peak attendance, workstation strategy, meeting rooms, private calls, circulation and support spaces rather than one sqft-per-person rule.',
    href: '/insights/how-much-office-space-do-you-need-singapore',
    linkLabel: 'Read office space planning guide',
    keywords: [
      'office space needed',
      'how big office',
      'office size headcount',
      'sqft per employee',
      'office for 20 people',
      'office for 40 staff',
      'how many seats office',
    ],
    category: 'Office Planning',
    relatedIds: ['office-space-planner'],
  },
  {
    id: 'office-space-planner',
    question: 'Can I calculate office size from my headcount and rooms?',
    answer:
      'Yes. The Office Space Planner estimates the space required from headcount, workstations, meeting rooms, private rooms and support spaces.',
    href: '/office-space-planner',
    linkLabel: 'Use Office Space Planner',
    keywords: [
      'office space calculator',
      'office size calculator',
      'headcount calculator',
      'calculate office space',
      'meeting room office size',
      'office space planner',
    ],
    category: 'Office Tool',
    relatedIds: ['office-space-needed'],
  },

  {
    id: 'fnb-before-signing-lease',
    question: 'What should I check before signing an F&B shop lease?',
    answer:
      'Confirm the approved use, landlord conditions and whether the unit can support your actual menu, cooking methods and equipment. Check exhaust, grease and wastewater management, electrical capacity, gas options, fire safety and SFA licensing before commitment.',
    href: '/insights/what-to-check-before-signing-fnb-shop-lease-singapore',
    linkLabel: 'Read F&B lease checklist',
    keywords: [
      'before signing F&B lease',
      'restaurant lease check',
      'cafe lease check',
      'F&B unit suitability',
      'food shop lease',
      'before renting restaurant',
      'F&B shop checklist',
    ],
    category: 'F&B Planning',
    relatedIds: ['fnb-heavy-cooking', 'fnb-exhaust-feasibility', 'fnb-grease-trap'],
  },
  {
    id: 'fnb-former-fnb-unit',
    question: 'If the unit was previously F&B, is it automatically suitable for my restaurant?',
    answer:
      'No. A previous F&B use is helpful evidence, but it does not prove the unit can support your menu, equipment or cooking method. Heavy wok cooking, grilling or baking can require very different exhaust, power, gas, drainage and fire-safety provisions.',
    href: '/insights/what-to-check-before-signing-fnb-shop-lease-singapore',
    linkLabel: 'Read F&B unit suitability guide',
    keywords: [
      'previous F&B unit',
      'former restaurant unit',
      'already F&B approved',
      'F&B unit suitable',
      'take over restaurant unit',
      'existing cafe unit',
    ],
    category: 'F&B Planning',
    relatedIds: ['fnb-heavy-cooking'],
  },
  {
    id: 'fnb-heavy-cooking',
    question: 'Can this F&B unit support heavy cooking?',
    answer:
      'This depends on the actual menu, cooking equipment, exhaust route, drainage, grease control, electrical or gas capacity and building restrictions. It should be checked before the lease is committed.',
    href: '/insights/what-to-check-before-signing-fnb-shop-lease-singapore',
    linkLabel: 'Read F&B feasibility guide',
    keywords: [
      'heavy cooking',
      'wok cooking unit',
      'restaurant heavy cooking',
      'can this shop cook',
      'commercial kitchen feasibility',
      'hotpot unit',
      'BBQ restaurant unit',
    ],
    category: 'Project Specific',
    projectSpecific: true,
    relatedIds: ['fnb-exhaust-feasibility', 'fnb-gas-options'],
  },
  {
    id: 'fnb-exhaust-feasibility',
    question: 'How do I know if an F&B unit can support kitchen exhaust?',
    answer:
      'The exhaust route and discharge feasibility should be checked before committing to the unit. The menu, cooking process, duct route, building restrictions and environmental requirements can all affect whether the proposed kitchen is workable.',
    href: '/insights/what-to-check-before-signing-fnb-shop-lease-singapore',
    linkLabel: 'Read F&B exhaust planning guide',
    keywords: [
      'kitchen exhaust',
      'restaurant exhaust',
      'F&B exhaust duct',
      'exhaust route',
      'commercial kitchen exhaust',
      'no exhaust restaurant',
      'recirculating hood',
    ],
    category: 'F&B Planning',
    projectSpecific: true,
    relatedIds: ['fnb-heavy-cooking'],
  },
  {
    id: 'fnb-grease-trap',
    question: 'Does an F&B unit need a grease trap?',
    answer:
      'Grease management is a key F&B planning requirement, and food premises commonly need suitable grease-trap arrangements subject to the actual operation and PUB requirements. The location and drainage setup should be checked before the kitchen layout is fixed.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read F&B approval requirements',
    keywords: [
      'grease trap',
      'restaurant grease trap',
      'F&B grease trap',
      'PUB grease trap',
      'food shop drainage',
      'grease interceptor',
    ],
    category: 'F&B Approval',
    projectSpecific: true,
  },
  {
    id: 'fnb-gas-options',
    question: 'Can my restaurant use gas or LPG?',
    answer:
      'Gas suitability cannot be confirmed from the floor area alone. The actual equipment, landlord rules, fire-safety requirements, ventilation and building services must be checked for the specific unit and concept.',
    href: '/insights/what-to-check-before-signing-fnb-shop-lease-singapore',
    linkLabel: 'Read F&B unit planning guide',
    keywords: [
      'restaurant gas',
      'LPG restaurant',
      'can use gas',
      'gas cooking F&B',
      'town gas restaurant',
      'gas cylinder restaurant',
    ],
    category: 'Project Specific',
    projectSpecific: true,
    relatedIds: ['fnb-heavy-cooking'],
  },
  {
    id: 'fnb-sfa-licence',
    question: 'When should I think about SFA licensing for an F&B renovation?',
    answer:
      'SFA licensing should be considered early because the kitchen, equipment layout, food flow, wash areas and other operational details can affect the submitted layout and pre-opening readiness.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read F&B approval pathway',
    keywords: [
      'SFA licence',
      'food shop licence',
      'restaurant licence',
      'cafe licence Singapore',
      'SFA renovation',
      'food licence before renovation',
    ],
    category: 'F&B Approval',
    relatedIds: ['fnb-before-signing-lease'],
  },

  {
    id: 'commercial-reinstatement',
    question: 'What is commercial reinstatement and when should I plan it?',
    answer:
      'Commercial reinstatement is the work required to return a leased unit to the condition required by the landlord at handover. It should be planned early because lease clauses, landlord standards, nominated contractors and handover inspections can affect cost and timing.',
    href: '/insights/commercial-reinstatement-singapore',
    linkLabel: 'Read commercial reinstatement guide',
    keywords: [
      'commercial reinstatement',
      'office reinstatement',
      'shop reinstatement',
      'return unit landlord',
      'lease handover renovation',
      'end of lease renovation',
      'restore office',
    ],
    category: 'Reinstatement',
  },
  {
    id: 'reinstatement-deposit',
    question: 'Can reinstatement problems affect my renovation deposit or lease handover?',
    answer:
      'Yes. Incomplete reinstatement, landlord comments, outstanding defects or uncoordinated handover items can delay acceptance and create deposit-recovery risk. The landlord’s required handover condition should be confirmed before work begins.',
    href: '/insights/commercial-reinstatement-singapore',
    linkLabel: 'Read reinstatement handover guide',
    keywords: [
      'renovation deposit',
      'reinstatement deposit',
      'deposit refund office',
      'landlord deposit renovation',
      'handover deposit',
      'reinstatement inspection',
    ],
    category: 'Reinstatement',
    relatedIds: ['commercial-reinstatement'],
  },

  {
    id: 'clinic-renovation-approval',
    question: 'Can I renovate a clinic like a normal office?',
    answer:
      'No. The healthcare services being provided can affect room functions, patient flow, plumbing, privacy, infection-control expectations, accessibility and licensing. The premises and renovation should be planned together with the applicable healthcare requirements.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read clinic approval pathway',
    keywords: [
      'clinic renovation',
      'medical clinic renovation',
      'HCSA clinic',
      'clinic approval Singapore',
      'clinic office conversion',
      'healthcare renovation',
    ],
    category: 'Unusual Commercial',
    projectSpecific: true,
  },
  {
    id: 'industrial-unit-approval',
    question: 'What should I check before renovating an industrial or warehouse unit?',
    answer:
      'Check the approved use, equipment loading, electrical power, ventilation, discharge, fire safety and landlord or JTC/HDB requirements before committing to heavy equipment or operational changes.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read industrial approval pathway',
    keywords: [
      'industrial renovation',
      'warehouse renovation',
      'JTC renovation',
      'factory renovation',
      'warehouse approval',
      'industrial unit fit out',
    ],
    category: 'Unusual Commercial',
    projectSpecific: true,
  },
  {
    id: 'cleaning-business-premises',
    question: 'Does a cleaning business need renovation approval for its office or storage space?',
    answer:
      'The business licence and premises approval are separate. A simple administrative office may follow a normal office pathway, while chemical, battery, machinery or equipment storage can trigger additional use, fire-safety, ventilation or landlord requirements.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read cleaning-business pathway',
    keywords: [
      'cleaning business renovation',
      'cleaning company office',
      'chemical storage office',
      'NEA cleaning licence premises',
      'cleaning company warehouse',
    ],
    category: 'Unusual Commercial',
    projectSpecific: true,
  },
  {
    id: 'childcare-premises',
    question: 'Can I convert a commercial unit into a childcare or preschool?',
    answer:
      'This requires more than ordinary renovation planning. Premises suitability, approved use, child-safety requirements, fire safety and ECDA licensing should be checked before committing to the unit.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read regulated-trade approval guide',
    keywords: [
      'childcare renovation',
      'preschool renovation',
      'ECDA premises',
      'convert office childcare',
      'childcare approval',
    ],
    category: 'Unusual Commercial',
    projectSpecific: true,
  },
  {
    id: 'beauty-gym-wellness',
    question: 'Do beauty, wellness or gym spaces follow normal retail renovation rules?',
    answer:
      'Not always. The actual service, approved use, wet areas, ventilation, noise and any sector-specific licence can change the approval and renovation pathway. The business activity should be defined before the layout is finalised.',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: 'Read regulated-trade approval guide',
    keywords: [
      'beauty salon renovation',
      'gym renovation',
      'wellness renovation',
      'massage shop renovation',
      'fitness studio approval',
      'beauty shop approval',
    ],
    category: 'Unusual Commercial',
    projectSpecific: true,
  },
];

const zh: AnswerFinderEntry[] = [
  {
    id: 'renovation-cost-singapore',
    question: '在新加坡装修大概要多少钱？',
    answer:
      '装修费用取决于房屋类型、屋况与工程范围。ID Work Studio 的 2026 指南提供 BTO、转售 HDB 与公寓的规划预算范围，可作为前期参考。',
    href: '/insights/renovation-cost-singapore-2026',
    linkLabel: '查看装修费用指南',
    keywords: ['装修费用', '装修多少钱', 'HDB 装修预算', 'BTO 装修费用', '转售屋装修', '公寓装修费用'],
    category: '住宅费用',
    relatedIds: ['kitchen-renovation-cost', 'quotation-differences', 'total-home-budget'],
  },
  {
    id: 'hdb-renovation-timeline',
    question: 'HDB 装修通常需要多久？',
    answer:
      '工期会受工程范围、审批、拆除、木工、材料与现场协调影响。建议按实际施工顺序和审批时间规划，而不是只看一个固定完工日期。',
    href: '/insights/hdb-renovation-timeline-singapore',
    linkLabel: '查看 HDB 工期指南',
    keywords: ['HDB 装修多久', '装修工期', 'BTO 装修时间', '转售屋装修时间', '什么时候可以入住'],
    category: '住宅工期',
    relatedIds: ['renovation-cost-singapore', 'hdb-defects-before-renovation'],
  },
  {
    id: 'quotation-differences',
    question: '为什么不同装修公司的报价差这么多？',
    answer:
      '很多时候是因为各家公司并没有报价同样的工程范围、材料、数量、风险与排除项目。比较时应该逐项对照，而不是只看最后总价。',
    href: '/insights/renovation-quotation-singapore',
    linkLabel: '查看报价比较指南',
    keywords: ['装修报价差很多', '比较报价', '为什么报价不同', '便宜报价', '装修公司报价'],
    category: '报价',
    relatedIds: ['variation-orders', 'renovation-cost-singapore'],
  },
  {
    id: 'variation-orders',
    question: '装修追加费用或 VO 正常吗？',
    answer:
      '有些追加费用来自拆除后才发现的隐藏问题，或业主后来改变工程范围，这些情况可能合理。真正要小心的是原报价故意漏掉必要项目，之后再逐项追加。',
    href: '/insights/renovation-quotation-singapore',
    linkLabel: '了解 VO 与追加费用',
    keywords: ['VO', '追加费用', '装修加钱', '额外收费', 'variation order'],
    category: '报价',
    relatedIds: ['quotation-differences'],
  },
  {
    id: 'hdb-defects-before-renovation',
    question: 'HDB 开始装修前应该检查什么？',
    answer:
      '大工程开始前应先检查并记录原有缺陷，例如水流、空鼓砖、门窗、水表电表、潮湿渗水与地面坡度，避免日后责任不清。',
    href: '/insights/hdb-defect-checklist-before-renovation-singapore',
    linkLabel: '查看 HDB 缺陷检查指南',
    keywords: ['HDB 缺陷', 'BTO 验屋', '装修前检查', '空鼓砖', '漏水', '缺陷清单'],
    category: '住宅规划',
    relatedIds: ['hdb-renovation-timeline'],
  },
  {
    id: 'overseas-renovation-items',
    question: '装修用品可以从淘宝或海外买吗？',
    answer:
      '可以，但要先确认尺寸、电梯与搬运限制、新加坡电压、适用的 SAFETY Mark 或 WELS 要求、保修、零件、运输损坏风险和到货时间。',
    href: '/insights/overseas-renovation-shopping-singapore',
    linkLabel: '查看海外采购指南',
    keywords: ['淘宝装修', '中国买家具', '海外电器', '进口水龙头', '海外瓷砖', '淘宝家具'],
    category: '住宅规划',
    relatedIds: ['hdb-renovation-timeline'],
  },
  {
    id: 'feng-shui-before-renovation',
    question: '装修前要先考虑风水吗？',
    answer:
      '如果风水会影响布局、灯光、收纳或动线，最好在木工和电气图纸确定前讨论。实际生活功能仍应优先于纯装饰性的象征。',
    href: '/insights/feng-shui-renovation-singapore',
    linkLabel: '查看装修风水指南',
    keywords: ['装修风水', 'HDB 风水', '装修前看风水', '风水布局'],
    category: '住宅规划',
  },
  {
    id: 'kitchen-renovation-cost',
    question: '厨房装修大概要多少钱？',
    answer:
      '厨房费用主要受拆除、铺砖、橱柜长度、台面材料、水电和原有现场状况影响。建议查看厨房费用指南的分项说明。',
    href: '/insights/kitchen-renovation-cost-singapore-2026',
    linkLabel: '查看厨房费用指南',
    keywords: ['厨房装修多少钱', '厨房装修费用', '橱柜费用', '厨房拆除', 'HDB 厨房'],
    category: '住宅费用',
    relatedIds: ['renovation-cost-singapore'],
  },
  {
    id: 'total-home-budget',
    question: '除了装修合同，还要准备多少搬家入住预算？',
    answer:
      '装修只是整体入住预算的一部分。家具、电器、费用、替换品和安全缓冲都会影响真正需要准备的现金。',
    href: '/insights/real-cost-moving-home-singapore',
    linkLabel: '查看完整入住预算指南',
    keywords: ['入住预算', '家具电器预算', '装修以外费用', '搬家多少钱', '需要准备多少现金'],
    category: '住宅费用',
    relatedIds: ['renovation-cost-singapore'],
  },
  {
    id: 'hdb-wall-hacking',
    question: '我的 HDB 这面墙可以拆吗？',
    answer:
      '这个问题不能靠一般网站内容安全确认。是否可以拆除取决于具体单位、批准图纸、结构性质与计划进行的工程。',
    href: '/residential',
    linkLabel: '查看住宅装修服务',
    keywords: ['HDB 拆墙', '这面墙可以拆吗', '结构墙', '拆除墙', '敲墙'],
    category: '项目专属',
    projectSpecific: true,
  },

  {
    id: 'commercial-renovation-cost',
    question: '新加坡商业装修大概要多少钱？',
    answer:
      '商业装修费用受行业类型、大厦规定、机电需求和审批影响。办公室、零售、诊所与餐饮即使面积相近，成本结构也可能完全不同。',
    href: '/insights/commercial-renovation-cost-singapore',
    linkLabel: '查看商业装修费用指南',
    keywords: ['商业装修费用', '店面装修多少钱', '零售装修费用', '商业装修每平方尺'],
    category: '商业费用',
    relatedIds: ['office-renovation-cost', 'fnb-renovation-cost'],
  },
  {
    id: 'office-renovation-cost',
    question: '新加坡办公室装修大概要多少钱？',
    answer:
      '办公室费用受装修等级、隔间、电气与网络、冷气、消防协调、材料与大厦要求影响。最新范围应以办公室费用指南按面积和工程范围判断。',
    href: '/insights/office-renovation-cost-singapore',
    linkLabel: '查看办公室费用指南',
    keywords: ['办公室装修费用', 'office fit out cost', '办公室每平方尺', '办公室装修预算'],
    category: '办公室费用',
    relatedIds: ['office-renovation-timeline', 'office-space-needed'],
  },
  {
    id: 'fnb-renovation-cost',
    question: '为什么餐饮装修通常比办公室贵？',
    answer:
      '餐饮项目通常需要更重的机电系统，例如排烟、隔油、给排水、防水、厨房设备与消防协调。这些技术工程往往比表面装修更影响预算。',
    href: '/insights/commercial-renovation-cost-singapore',
    linkLabel: '查看餐饮与商业费用指南',
    keywords: ['餐饮装修费用', '餐厅装修贵', '咖啡店装修费用', 'F&B 装修'],
    category: '餐饮费用',
    relatedIds: ['fnb-before-signing-lease', 'fnb-exhaust-feasibility'],
  },
  {
    id: 'office-renovation-timeline',
    question: '办公室装修通常需要多久？',
    answer:
      '作为规划参考，小型办公室约 3–6 周，中型约 6–10 周，大型或企业办公室约 10–16 周；这些时间包括规划、审批、施工与交付。',
    href: '/insights/office-renovation-timeline-singapore',
    linkLabel: '查看办公室工期指南',
    keywords: ['办公室装修多久', '办公室工期', 'office fit out 时间', '办公室什么时候能搬入'],
    category: '办公室工期',
    relatedIds: ['office-two-week-renovation', 'office-renovation-cost'],
  },
  {
    id: 'office-two-week-renovation',
    question: '办公室装修可以两周完成吗？',
    answer:
      '只有非常小型、以表面更新为主的工程才有可能接近两周。若涉及隔间、电气、网络、冷气和大厦审批，通常需要更长时间。',
    href: '/insights/office-renovation-timeline-singapore',
    linkLabel: '查看实际办公室工期',
    keywords: ['两周办公室装修', '快速办公室装修', '赶工办公室', '办公室急着完工'],
    category: '办公室工期',
    relatedIds: ['office-renovation-timeline'],
  },
  {
    id: 'office-operate-during-renovation',
    question: '办公室装修期间可以继续营业或办公吗？',
    answer:
      '有些情况可以，但需要分阶段施工、控制灰尘与噪音、做好安全隔离，并安排电源和网络切换。有人办公的施工通常比空置单位更慢。',
    href: '/insights/office-renovation-timeline-singapore',
    linkLabel: '查看营业期间施工规划',
    keywords: ['装修期间办公', '边装修边上班', '办公室继续营业', '分阶段装修'],
    category: '办公室工期',
    relatedIds: ['office-after-hours-renovation'],
  },
  {
    id: 'office-after-hours-renovation',
    question: '办公室可以晚上或周末装修吗？',
    answer:
      '如果大厦允许，一般可以。但夜间、周末和噪音工程可能需要额外审批，也可能增加人工成本或拉长工期。',
    href: '/insights/office-renovation-timeline-singapore',
    linkLabel: '查看办公室工期指南',
    keywords: ['晚上装修', '周末装修', '夜间施工', '噪音工程时间', 'after hours renovation'],
    category: '办公室工期',
    relatedIds: ['office-renovation-timeline'],
  },
  {
    id: 'office-landlord-approval',
    question: '办公室装修需要业主或大厦管理处批准吗？',
    answer:
      '通常需要。大多数办公室装修在开工前都要经过业主或大厦管理处审核，并可能要求图纸、施工计划、method statement、承包商资料和保险文件。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看商业审批指南',
    keywords: ['业主批准装修', '管理处批准', '办公室装修准证', 'permit to work'],
    category: '商业审批',
    relatedIds: ['office-mcst-approval', 'office-scdf-approval'],
  },
  {
    id: 'office-mcst-approval',
    question: '办公室装修需要 MCST 批准吗？',
    answer:
      '如果办公室位于分层产权物业，通常需要 MCST 或管理代理在施工前批准。实际文件要求要按该大厦规定确认。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看商业审批指南',
    keywords: ['MCST 装修批准', 'MCST 办公室', '管理代理批准', 'strata office'],
    category: '商业审批',
    relatedIds: ['office-landlord-approval', 'office-scdf-approval'],
  },
  {
    id: 'office-scdf-approval',
    question: '办公室装修需要消防或 SCDF 批准吗？',
    answer:
      '如果工程影响隔间、逃生路线、防火构件、喷淋、警报、烟感或人员负荷，可能需要 SCDF 相关审核。具体单位应由合适的 Qualified Person 按实际工程判断。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看 SCDF 与审批指南',
    keywords: ['办公室消防批准', 'SCDF 办公室', '消防准证', '喷淋审批', 'fire approval'],
    category: '商业审批',
    relatedIds: ['office-landlord-approval', 'commercial-skip-scdf'],
    projectSpecific: true,
  },
  {
    id: 'commercial-skip-scdf',
    question: '简单商业装修可以不做 SCDF submission 吗？',
    answer:
      '只有在工程确实属于表面装修，并且没有影响消防系统或防火要求时才可能不需要。若涉及隔间、天花、喷淋、警报、逃生路线或防火构件，就可能触发相关 submission。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看 SCDF 审批指南',
    keywords: ['不做 SCDF', '简单装修 SCDF', 'SCDF 可以跳过吗', '消防 submission'],
    category: '商业审批',
    projectSpecific: true,
  },
  {
    id: 'commercial-permit-rejected',
    question: '如果 MCST 或管理处拒绝装修准证怎么办？',
    answer:
      '在申请被接受之前，工程不能正式开始。常见原因包括图纸不完整、保险或文件缺失、承包商资料不符合要求，或计划工程违反大厦规定。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看审批问题指南',
    keywords: ['装修准证被拒', 'MCST 拒绝', '管理处不批准', 'permit rejected'],
    category: '商业审批',
    relatedIds: ['office-landlord-approval'],
  },
  {
    id: 'commercial-rent-free-period',
    question: '一个月免租装修期够吗？',
    answer:
      '不一定。测量、设计、管理处审核、保险、押金和开工准证都可能先消耗免租期，真正施工可能比你预期更晚开始。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看租约到开业规划',
    keywords: ['免租装修期', '一个月免租', 'fit out period', '装修免租期够吗'],
    category: '商业规划',
    relatedIds: ['commercial-before-lease', 'office-renovation-timeline'],
  },
  {
    id: 'commercial-before-lease',
    question: '签商业租约前应该先检查什么？',
    answer:
      '先确认单位是否适合你的行业用途，取得最新 fit-out guide，并检查电力、冷气、排水、排烟、结构限制和可能涉及的审批路径，再决定开业时间。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看商业单位规划指南',
    keywords: ['签商业租约前', '租店前检查', '商业单位适合吗', '接手单位前'],
    category: '商业规划',
    relatedIds: ['fnb-before-signing-lease', 'commercial-rent-free-period'],
  },
  {
    id: 'office-space-needed',
    question: '我需要多大的办公室？',
    answer:
      '办公室面积应该按人数、最高出勤人数、工位模式、会议室、私人通话、走道与后勤空间来规划，而不是只套一个每人多少平方尺的公式。',
    href: '/insights/how-much-office-space-do-you-need-singapore',
    linkLabel: '查看办公室面积规划指南',
    keywords: ['办公室多大', '多少平方尺办公室', '每人办公室面积', '40 人办公室', 'office size'],
    category: '办公室规划',
    relatedIds: ['office-space-planner'],
  },
  {
    id: 'office-space-planner',
    question: '可以用人数和房间数量计算办公室面积吗？',
    answer:
      '可以。Office Space Planner 会按人数、工位、会议室、私人房间和支援空间估算所需面积。',
    href: '/office-space-planner',
    linkLabel: '使用 Office Space Planner',
    keywords: ['办公室面积计算器', '人数计算办公室', 'office space planner', '办公室规划工具'],
    category: '办公室工具',
    relatedIds: ['office-space-needed'],
  },

  {
    id: 'fnb-before-signing-lease',
    question: '签餐饮店租约前应该检查什么？',
    answer:
      '先确认批准用途、业主条件，以及单位是否真的能支持你的菜单、烹饪方式与设备。排烟、隔油和废水、电力、燃气、消防与 SFA 执照都应该在签约前考虑。',
    href: '/insights/what-to-check-before-signing-fnb-shop-lease-singapore',
    linkLabel: '查看餐饮租约检查指南',
    keywords: ['签餐饮租约前', '餐厅租店检查', 'F&B 单位适合吗', '咖啡店租约'],
    category: '餐饮规划',
    relatedIds: ['fnb-heavy-cooking', 'fnb-exhaust-feasibility', 'fnb-grease-trap'],
  },
  {
    id: 'fnb-former-fnb-unit',
    question: '以前是餐饮店的单位，就一定适合我的餐厅吗？',
    answer:
      '不一定。以前做过餐饮只是有利条件，并不能证明它适合你的菜单、设备或烹饪方式。重油烟、烧烤、烘焙等对排烟、电力、燃气、排水和消防的要求可能完全不同。',
    href: '/insights/what-to-check-before-signing-fnb-shop-lease-singapore',
    linkLabel: '查看餐饮单位适用性指南',
    keywords: ['以前是餐厅', '旧 F&B 单位', '原本咖啡店', '餐饮单位接手'],
    category: '餐饮规划',
    relatedIds: ['fnb-heavy-cooking'],
  },
  {
    id: 'fnb-heavy-cooking',
    question: '这个餐饮单位可以做重油烟或重煮食吗？',
    answer:
      '要看实际菜单、设备、排烟路线、排水、隔油、电力或燃气容量以及大厦限制。这个问题应该在签租约前按具体单位确认。',
    href: '/insights/what-to-check-before-signing-fnb-shop-lease-singapore',
    linkLabel: '查看餐饮单位可行性指南',
    keywords: ['重油烟', '重煮食', '炒锅餐厅', '烧烤店', '火锅店', '商业厨房'],
    category: '项目专属',
    relatedIds: ['fnb-exhaust-feasibility', 'fnb-gas-options'],
    projectSpecific: true,
  },
  {
    id: 'fnb-exhaust-feasibility',
    question: '怎么知道餐饮单位能不能做厨房排烟？',
    answer:
      '签约前应先确认排烟路线和排放可行性。菜单、烹饪方式、风管路线、大厦限制与环境要求都会影响厨房是否可行。',
    href: '/insights/what-to-check-before-signing-fnb-shop-lease-singapore',
    linkLabel: '查看餐饮排烟规划指南',
    keywords: ['厨房排烟', '餐厅排烟', '排烟管', '商业厨房排烟', 'recirculating hood'],
    category: '餐饮规划',
    relatedIds: ['fnb-heavy-cooking'],
    projectSpecific: true,
  },
  {
    id: 'fnb-grease-trap',
    question: '餐饮单位一定要有隔油池吗？',
    answer:
      '隔油管理是餐饮规划的重要部分，食肆通常需要合适的隔油安排，并按实际经营和 PUB 要求确认。厨房布局确定前就应该检查位置和排水条件。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看餐饮审批要求',
    keywords: ['隔油池', 'grease trap', '餐厅排水', 'PUB 隔油池', '隔油器'],
    category: '餐饮审批',
    projectSpecific: true,
  },
  {
    id: 'fnb-gas-options',
    question: '我的餐厅可以使用煤气或 LPG 吗？',
    answer:
      '不能只按面积判断。具体设备、业主规定、消防要求、通风和大厦系统都要按这个单位与餐饮概念确认。',
    href: '/insights/what-to-check-before-signing-fnb-shop-lease-singapore',
    linkLabel: '查看餐饮单位规划指南',
    keywords: ['餐厅煤气', 'LPG 餐厅', '可以用 gas 吗', '燃气煮食'],
    category: '项目专属',
    relatedIds: ['fnb-heavy-cooking'],
    projectSpecific: true,
  },
  {
    id: 'fnb-sfa-licence',
    question: '餐饮装修什么时候要开始考虑 SFA 执照？',
    answer:
      '应该很早就考虑，因为厨房、设备布局、食物流线、清洗区域等会影响提交图纸和开业前准备。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看餐饮审批路径',
    keywords: ['SFA 执照', 'food shop licence', '餐厅执照', '咖啡店执照'],
    category: '餐饮审批',
    relatedIds: ['fnb-before-signing-lease'],
  },

  {
    id: 'commercial-reinstatement',
    question: '什么是商业 reinstatement，什么时候要开始规划？',
    answer:
      '商业 reinstatement 是按租约和业主要求，把租赁单位恢复到指定交还状态。租约条款、业主标准、指定承包商和交场检查都会影响费用和时间，所以应尽早规划。',
    href: '/insights/commercial-reinstatement-singapore',
    linkLabel: '查看商业 reinstatement 指南',
    keywords: ['商业 reinstatement', '办公室恢复原状', '店铺恢复原状', '租约交还', '办公室退租'],
    category: '恢复原状',
  },
  {
    id: 'reinstatement-deposit',
    question: '恢复原状做不好会影响押金或交场吗？',
    answer:
      '会。未完成的恢复工程、业主意见、缺陷或交场项目都可能延迟验收并影响押金处理。施工前就应该确认业主要求的最终交还状态。',
    href: '/insights/commercial-reinstatement-singapore',
    linkLabel: '查看 reinstatement 交场指南',
    keywords: ['装修押金', 'reinstatement 押金', '办公室押金退回', '交场验收'],
    category: '恢复原状',
    relatedIds: ['commercial-reinstatement'],
  },

  {
    id: 'clinic-renovation-approval',
    question: '诊所可以像普通办公室一样装修吗？',
    answer:
      '不可以简单当成普通办公室。医疗服务内容会影响房间功能、病人动线、给排水、私隐、感染控制、无障碍和执照要求。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看诊所审批路径',
    keywords: ['诊所装修', 'clinic renovation', 'HCSA', '医疗诊所审批'],
    category: '特殊商业',
    projectSpecific: true,
  },
  {
    id: 'industrial-unit-approval',
    question: '工业或仓库单位装修前要检查什么？',
    answer:
      '应先确认批准用途、设备荷载、电力、通风、排放、消防以及 JTC、HDB 或业主要求，再决定重型设备和实际经营方式。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看工业单位审批路径',
    keywords: ['工业装修', '仓库装修', 'JTC 装修', 'factory renovation', '工业单位'],
    category: '特殊商业',
    projectSpecific: true,
  },
  {
    id: 'cleaning-business-premises',
    question: '清洁公司办公室或储物空间需要装修审批吗？',
    answer:
      '清洁业务执照和场地审批是两回事。普通行政办公室可能走一般办公室路径，但若储存化学品、电池、机器或设备，就可能涉及额外用途、消防、通风和业主要求。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看清洁行业审批路径',
    keywords: ['清洁公司装修', '清洁公司办公室', '化学品储存', 'NEA cleaning licence'],
    category: '特殊商业',
    projectSpecific: true,
  },
  {
    id: 'childcare-premises',
    question: '商业单位可以改成托儿所或幼儿园吗？',
    answer:
      '这不只是普通装修问题。签约前要检查场地适用性、批准用途、儿童安全、消防与 ECDA 执照要求。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看特殊行业审批指南',
    keywords: ['托儿所装修', '幼儿园装修', 'ECDA 场地', 'childcare renovation'],
    category: '特殊商业',
    projectSpecific: true,
  },
  {
    id: 'beauty-gym-wellness',
    question: '美容、养生或健身房可以按普通零售装修处理吗？',
    answer:
      '不一定。实际服务内容、批准用途、湿区、通风、噪音和行业执照都可能改变审批与装修路径，因此应先明确经营内容再定布局。',
    href: '/insights/commercial-renovation-approvals-singapore',
    linkLabel: '查看特殊行业审批指南',
    keywords: ['美容院装修', '健身房装修', '养生馆装修', '按摩店装修', 'gym renovation'],
    category: '特殊商业',
    projectSpecific: true,
  },
];

export const answerFinderIndex: Record<AnswerFinderLanguage, AnswerFinderEntry[]> = {
  en,
  zh,
};

export const homepageSuggestedAnswerIds: Record<AnswerFinderLanguage, string[]> = {
  en: [
    'renovation-cost-singapore',
    'hdb-renovation-timeline',
    'office-renovation-cost',
    'office-scdf-approval',
    'office-space-needed',
    'fnb-before-signing-lease',
  ],
  zh: [
    'renovation-cost-singapore',
    'hdb-renovation-timeline',
    'office-renovation-cost',
    'office-scdf-approval',
    'office-space-needed',
    'fnb-before-signing-lease',
  ],
};

export function getAnswerFinderEntries(language: string): AnswerFinderEntry[] {
  return answerFinderIndex[language === 'zh' ? 'zh' : 'en'];
}

export function getHomepageSuggestedAnswerIds(language: string): string[] {
  return homepageSuggestedAnswerIds[language === 'zh' ? 'zh' : 'en'];
}
